server:
  port: 8001

#mybatis 配置
mybatis:
  type-aliases-package: com.rango.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

#spring的配置:
spring:
  application:
    name: springcloud-provider-dept-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scdb01?serverTimezone=GMT
    username: root
    password: meng1314

#Eureka配置  服务注册到哪
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-provider-dept8001
info:
  app.name: rango-springcloud
  company.name: rango.com
